title: TA Wiki
description: An Unofficial Wiki for the Technical Assistant team at Asia Pacific University
theme: just-the-docs

logo: "/assets/images/ta-wiki.png"
favicon_ico: "/assets/images/favicon.ico"

url: https://ta-wiki.nodr.me

color-scheme: auto

aux_links:
  APU Homepage: https://www.apu.edu.my

# Enable search functionality
search_enabled: true

# Enable copy code button for code blocks
enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2025 APU Technical Assistant Team."

# Enable callouts
callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  highlight:
    color: yellow
